
spring:
  profiles:
    active:
    - dev
  datasource:
    url: jdbc:mysql://192.168.1.17:3306/BankManager-dev?serverTimezone=UTC
    username: bankmanager-dev
    password: bankmanager-dev
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    contexts: dev
  security:
    user:
      name: admin
      password: admin
      roles:
      - ADMIN